version: '3.8'

services:
  express-server:
    build:
      context: ../..
      dockerfile: servers/express/Dockerfile
    ports:
      - "4021:4021"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4021/weather"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
